package com.kftc.openbankingsample2.biz.self_auth;

/**
 * 자체인증 상수값
 */
public interface SelfAuthConst {

    public static String ACTIONBAR_TITLE = "ACTIONBAR_TITLE";


    // 설정 화면에서 저장되는 환경값
    // ex) 리얼이면 CLIENT_ID_REAL, 테스트이면 CLIENT_ID_TEST 로 저장된다.
    // 기본값은 CenterAuthSettingFragment.class 에서 설정하고, 앱구동시 AppData.class 의 PreferenceManager.setDefaultValues 에 의해 불려진다.
    // 따라서 여기 값이 변경되면 CenterAuthSettingFragment.class 의 xml 파일에 있는 key값도 같이 변경되어야 한다.
    
    String SELF_AUTH_IS_REAL = "SELF_AUTH_IS_REAL";
    String SELF_AUTH_BASE_URI = "SELF_AUTH_BASE_URI";
    String SELF_AUTH_CLIENT_ID = "SELF_AUTH_CLIENT_ID";
    String SELF_AUTH_CLIENT_SECRET = "SELF_AUTH_CLIENT_SECRET";
    String SELF_AUTH_CLIENT_USE_CODE = "SELF_AUTH_CLIENT_USE_CODE";
    String SELF_AUTH_REDIRECT_URI = "SELF_AUTH_REDIRECT_URI";
    String SELF_AUTH_CONTRACT_WITHDRAW_ACCOUNT_NUM = "SELF_AUTH_CONTRACT_WITHDRAW_ACCOUNT_NUM";
    String SELF_AUTH_CONTRACT_DEPOSIT_ACCOUNT_NUM = "SELF_AUTH_CONTRACT_DEPOSIT_ACCOUNT_NUM";

    // 기타 화면에서 저장되는 환경값
    String SELF_AUTH_ACCESS_TOKEN = "SELF_AUTH_ACCESS_TOKEN";
    String SELF_AUTH_ACCESS_TOKEN_LIST = "SELF_AUTH_ACCESS_TOKEN_LIST";
    String SELF_AUTH_BANK_ACCOUNT_LIST = "SELF_AUTH_BANK_ACCOUNT_LIST";
    String SELF_AUTH_FINTECH_USE_NUM = "SELF_AUTH_FINTECH_USE_NUM";
    String SELF_AUTH_CNTR_ACCOUNT_NUM = "SELF_AUTH_CNTR_ACCOUNT_NUM";
    String SELF_AUTH_BANK_CODE = "SELF_AUTH_BANK_CODE";
    String SELF_AUTH_ACCOUNT_NUM = "SELF_AUTH_ACCOUNT_NUM";
    String SELF_AUTH_USER_SEQ_NO = "SELF_AUTH_USER_SEQ_NO";
    String SELF_AUTH_ACCOUNT_HOLDER_INFO_TYPE_POSITION = "SELF_AUTH_ACCOUNT_HOLDER_INFO_TYPE_POSITION";
    String SELF_AUTH_ACCOUNT_HOLDER_INFO = "SELF_AUTH_ACCOUNT_HOLDER_INFO";
    String SELF_AUTH_USER_CI = "SELF_AUTH_USER_CI";
    String SELF_AUTH_USER_INFO = "SELF_AUTH_USER_INFO";
    String SELF_AUTH_USER_NAME = "SELF_AUTH_USER_NAME";
    String SELF_AUTH_USER_EMAIL = "SELF_AUTH_USER_EMAIL";
    String SELF_AUTH_REQ_CLIENT_NAME = "SELF_AUTH_REQ_CLIENT_NAME";
    String SELF_AUTH_REQ_CLIENT_BANK_CODE = "SELF_AUTH_REQ_CLIENT_BANK_CODE";
    String SELF_AUTH_REQ_CLIENT_ACCOUNT_NUM = "SELF_AUTH_REQ_CLIENT_ACCOUNT_NUM";
    String SELF_AUTH_BANK_TRAN_DATE = "SELF_AUTH_BANK_TRAN_DATE";
    String SELF_AUTH_ORG_BANK_TRAN_DATE = "SELF_AUTH_ORG_BANK_TRAN_DATE";

    // 번들 데이터 key
    String BUNDLE_KEY_ACCESS_TOKEN = "BUNDLE_KEY_ACCESS_TOKEN";
    String BUNDLE_KEY_IS_FINTECH_USE_NUM = "BUNDLE_KEY_IS_FINTECH_USE_NUM";

}
